//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dia11v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web
    {
        public int id { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> Kilometros { get; set; }
        public Nullable<decimal> Precio { get; set; }
    }
}
